### ISSUE TITLE
not working on mac os

### ISSUE THREAD

**Issue by RyonaBoy** [tomwillow/tomsolver#4]
<img width="1515" alt="Bildschirmfoto 2023-12-24 um 13 28 48" src="https://github.com/tomwillow/tomsolver/assets/11089160/bf89ac2d-4fc3-4754-8886-45f3c1cbaef3">

**Comment by tomwillow** [comment]
Thank for your issue!
I have got this. After fixed I will notify you.

**Comment by tomwillow** [comment]
I have added more automatically tests for MacOS, and modify code.
![image](https://github.com/tomwillow/tomsolver/assets/14949002/3a517e0a-5e63-4d1a-8367-10347d0bdd3b)

You could re-clone code from master branch to try again.
